### PR TITLE
Added GNOME 42 compatibility

### PR DESCRIPTION
**Pull request by jibsaram**
GNOME 42 is out, and your wonderful extension seems to be working great with it, still. I've tested it with the just-released Fedora 36. I have not tested it with Ubuntu 22.04 and the Pop_Os! equivalent, but I suspect it will run just as well there, too.

I've also gone ahead and bumped the version, but please let me know if I shouldn't do that for these kinds of updates.

Thank you!

### CODE REVIEW

**Comment by lunananananananana** [comment]
Thanks! I'd have done this myself a lot earlier, but I've switched to Fedora Silverblue since the last update and haven't figured out how to install the kernel module on there yet, so I wasn't able to test.

As for the version bump, that's ok, I'd have had to bump it myself anyway

**Comment by lunananananananana** [comment]
Submitted to EGO: https://extensions.gnome.org/review/32240

**Comment by jibsaram** [comment]
> I've switched to Fedora Silverblue since the last update and haven't figured out how to install the kernel module on there yet

Oh interesting, I had been curious about trying out Silverblue too, but not having the module available would be quite a big limitation for me. I wonder if it would require packaging up the kernel module so you could rely on [rpm-ostree](https://rpm-ostree.readthedocs.io/en/latest/) to have it installed and working? 

I'm still on Fedora Workstation on both my main machine and Zenbook, so have no direct experience with Silverblue yet. I suppose that may stay this way too, as it sounds nice in theory but in practice it just would end up requiring extra fiddling to get things working. And if there's one thing I'd rather not spend my time on.. :D

Thanks for approving the PR and for submitting the extension update!

**Comment by lunananananananana** [comment]
Yeah packaging it as RPM would probably work, but I have no experience with that since I'm still pretty new to RPM-based distros (came from Arch and Debian-based before that)

As for fiddling, yeah some things (mostly just IDEs) require a bit of work, but it's not too bad IMO. And in some cases (like GNOME Builder) everything works out of the box since it integrates Flatpak really well

**Pull request merged**
